repolinter-rulesets/community-plus.json, repolinter-rulesets/new-relic-one-catalog-project.json
This PR adds Repolinter rulesets for NR1 Catalog repositories and Community plus repositories. In addition to this PR, `master` branch should also be removed and the default branch set to `main`.
=> docs: Add community plus and nr1 catalog Repolinter rulesets

.github/workflows/test.yml, README.md, repolinter-rulesets/community-plus.json, repolinter-rulesets/new-relic-one-catalog-project.json
This PR updates the community plus ruleset to reflect changes suggested by @elucus:
* The GitHub actions check has been removed to account for teams still using other CI providers
* The security section check has been refactored into a security policy link check to better align with the [Open By Default](https://github.com/newrelic/open-by-default) template.
In addition to these changes, the NR1 catalog ruleset was updated to include a security policy link check, additional ruleset description was added to the README, and a CI check was added to verify that all rulesets do not cause repolinter-action to throw an error.
=> feat: Update community plus and NR1 catalog ruleset, add CI smoke test for rulesets

README.md, repolinter-rulesets/community-plus.yml, repolinter-rulesets/new-relic-one-catalog-project.json
This PR adds support for relative security policy URLs (`../../security/policy`).
=> fix: update security link policy to check for relative URLs

repolinter-rulesets/community-plus.yml
This PR addresses the possibility that a project may not require a `THIRD_PARTY_NOTICES` file by downgrading the rule to a warning.
=> fix: downgrade third-party-notices to warning

README.md, repolinter-rulesets/community-plus.yml, repolinter-rulesets/new-relic-one-catalog-project.json
This PR rolls out a policy change to centralize the code of conduct in this repository. The added rule, `code-of-conduct-file-does-not-exist`, checks that a code of conduct file is present and suggests it be removed if so.
=> feat: add code of conduct rule to nr1 catalog and community plus rulesets

.github/workflows/repolinter-apply.yml
This PR creates a centralized Repolinter Action deployment for projects that face difficulties merging PRs (such as https://github.com/newrelic/newrelic-python-agent). This deployment runs once a day or on push to `main`.
=> feat: add centralized repolinter-action deployment for python agent

README.md, repolinter-rulesets/community-plus.yml
This PR adds support for reStructured text to the community plus header check, allowing projects such as [newrelic-python-agent](https://github.com/newrelic/newrelic-python-agent) to use this alternate syntax for their README.
=>  fix: update community plus header check to support RST

.github/workflows/repolinter-apply.yml, repolinter-rulesets/community-plus.yml, repolinter-rulesets/new-relic-one-catalog-project.json
This PR addresses an issue seen in [this `Apply Repolinter` workflow run](https://github.com/newrelic/.github/actions/runs/248280255) where raw.githubusercontent.com does not serve the latest changes until after the repolinter action workflow has pulled the configuration. This desync causes repolinter action to use the configurations from the previous commit instead of the one just pushed, creating unnecessary issue noise. To address this problem, the `Apply Repolinter` workflow has been adjusted to extract configurations using a git checkout, which should always fetch the latest version.
In addition to the above changes, the `code-of-conduct-file-does-not-exist` rule has been fixed to point to the correct policy document.
=> fix: Update repolinter workflow to checkout config instead of pulling from githubusercontent

README.md, repolinter-rulesets/community-plus.yml, repolinter-rulesets/example-code.yml, repolinter-rulesets/new-relic-one-catalog-project.json
This PR adds a ruleset for the example code category. In addition, some clarity updates were made to the NR1 catalog and Community Plus rulesets.
=> feat: Add example code ruleset

.github/workflows/test.yml, README.md, repolinter-rulesets/new-relic-experimental.yml
This PR adds a repolinter ruleset for the new-relic-experimental category.
=> feat: add new-relic-experimental ruleset

README.md, repolinter-rulesets/new-relic-experimental.yml
This PR fixes a bug with the security policy link rule for newrelic-experminental.
=> fix: update experimental ruleset to point to newrelic-experimental org

.github/workflows/repolinter-apply.yml
Added the newrelic/opentelemetry-exporter-python repo to the list of repos in the repolinter-apply.yml file.
=> Update repolinter-apply.yml to include Python OTel exporter repo

repolinter-rulesets/nr1-lib-deprecations.yml
This change updates the regex to only flag dropdown components from the nr1 package.
=> chore: updated dropdown rule regex

repolinter-rulesets/community-plus.yml, repolinter-rulesets/community-project.yml, repolinter-rulesets/example-code.yml, repolinter-rulesets/new-relic-experimental.yml
This supercedes #30 as it updates all of the rulesets to use `main` instead of `master` in URL regexes for image headers, as the ones on `main` are better than the ones on `master`
Addresses #31 and https://github.com/newrelic/node-newrelic/issues/1394
=> Update rulesets to use images from main instead of master

repolinter-rulesets/community-plus.yml
Updates the `third-party-notices-exist` rule to allow the `THIRD_PARTH_NOTICES` file to exist either in root of the repo or in a `Licenses` folder. 
This is to mitigate [false-positive reports](https://github.com/newrelic/newrelic-dotnet-agent/issues/1706) when running RepoLinter on the .NET Agent repo, which maintains [`Licenses/THIRD_PARTY_NOTICES.txt`](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/licenses/THIRD_PARTY_NOTICES.txt)
=> chore: Additional valid location for THIRD_PARTY_NOTICES

.github/workflows/fossa.yml
This adds a workflow that will pull the latest FOSSA CLI and run `fossa analyze`  on the currently checked out branch. 
`fossa analyze` will scan the repo and submit results to app.fossa.com, without blocking a merge.
This workflow is intended to be used in an organization-side repo ruleset that will enforce its use on all repos.
=> Add workflow for fossa analyze

.github/workflows/fossa-caos.yml, .github/workflows/fossa-default.yml, .github/workflows/fossa-elixir.yml, .github/workflows/fossa-gradle.yml, .github/workflows/fossa-ruby-bundler.yml, .github/workflows/fossa-scala.yml
PRs from forks do not have access to secrets on the base repository. This checks if the API token is set in the `secrets` context. If not, this means the PR is from an external repo. In this case the workflow skips the FOSSA job. 
Also delete the `strategy` key which is only used if `matrix` is defined.
=> Skip FOSSA for forks

.github/workflows/fossa-caos.yml, .github/workflows/fossa-default.yml, .github/workflows/fossa-elixir.yml, .github/workflows/fossa-gradle.yml, .github/workflows/fossa-ruby-bundler.yml, .github/workflows/fossa-scala.yml
- Add team name flag to `fossa analyze`
- Delete unsupported triggers (see [docs for supported event triggers](https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#supported-event-triggers)
- Fix `if` block for `fossa job` to check string value of API key flag
=> specify team name for fossa analyze

.github/composite/fossa-composite/action.yml, .github/workflows/fossa-caos.yml, .github/workflows/fossa-check-env.yml, .github/workflows/fossa-default.yml, .github/workflows/fossa-elixir.yml, .github/workflows/fossa-gradle.yml, .github/workflows/fossa-ruby-bundler.yml, .github/workflows/fossa-scala.yml
Refactor all workflows to pull out duplicate code from `check_env` and `fossa` jobs. Fix bugs that suppressed errors from FOSSA analyze, and incorrectly set the `fossaAnalyzeResult` custom property. 
- Pull out FOSSA CLI duplicated code into a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) at [.github/composite/fossa-composite/action.yml](https://github.com/newrelic/.github/blob/a95054112259edb031c2147731bd054fc97e36e5/.github/composite/fossa-composite/action.yml). 
- A composite action enables the FOSSA steps to be called in the same job as the calling job. This allows the FOSSA CLI to to run after required configuration steps such as installing package managers. 
- Pull out `check-env` duplicated code into a [reusable …
=> Refactor check env and fossa cli

.github/workflows/fossa-caos.yml, .github/workflows/fossa-default.yml, .github/workflows/fossa-elixir.yml, .github/workflows/fossa-gradle.yml, .github/workflows/fossa-ruby-bundler.yml, .github/workflows/fossa-scala.yml
- In `fossa-scala.yml`, correct the condition to check for newrelic-java-tests repo
- If fossa-list-targets does not find targets, set fossaAnalyzeResult to "N/A"
- currently fossaAnalyzeResult has the default value of "Error" for repos without targets. Changing to "N/A" makes the data more clear. 
- this change does not affect whether the workflow passes or fails 
- In all workflows, move variables for custom properties from step outputs to a job environment variable in order to simplify sharing the values across workflow steps. 
- Add descriptor to workflow name, i.e. ` FOSSA CLI Analysis - Gradle ` 
- standardize grep for error logs to be `grep -i error` (case insensitive)
=> Fixes: scala for java tests, set fossaAnalyzeResult to N/A

.github/workflows/fossa-ruby-bundler.yml
- checkout@v3 uses a deprecated Node.js v16 runtime and should be updated to v4
- Ruby 3.3 (not 3.2) is the latest stable Ruby, so update setup-ruby to use v3.3
- We have multiple public Ruby repos that have `Gemfile.lock` intentionally ignored by Git, but FOSSA wants that file so autogenerate it running `bundle lock` where appropriate
- Do not run `bundle lock` if a lock file already exists
- Handle multiple `Gemfile` locations (the NR Ruby agent has 2)
- Ignore the `test/` and `spec/` directories
=> Ruby workflow enhancements

.github/composite/fossa-composite/action.yml
The if the FOSSA CLI errors, the check shows up as a red X on all PRs, in particular PRs to public repos. We want to suppress these so that contributors and consumers do not need to worry about the checks, for the following reasons:
- scans do not address security risk
- rulesets are still in the Evaluation period
- the failing check is not the fault of external contributors.
Errors will still be logged to the job logs.
=> FOSSA composite action exit code

SECURITY.md
Slight edits to SECURITY.md to change references from HackerOne to BugCrowd.
=> Update SECURITY.md to reference BugCrowd
